export const light = "#FDFDFD"
export const graylight = "#EAEAEA"
export const graydark = "#40464A"
export const dark = "#2F3438"
export const darker = "#2B2B2B"
export const pink = "#EA508F"
export const green = "#46AF46"
export const yellow = "#F2B827"